// This file is autogenerated. Changes will be overwritten.
#include "YPKJ5OE7LN/moc_CapturePanel.cpp"
#include "YPKJ5OE7LN/moc_ColorInputCard.cpp"
#include "YPKJ5OE7LN/moc_CombinationPanel.cpp"
#include "YPKJ5OE7LN/moc_DynamicInputPanel.cpp"
#include "YPKJ5OE7LN/moc_EstimateResultPanel.cpp"
#include "YPKJ5OE7LN/moc_MainWindow.cpp"
#include "YPKJ5OE7LN/moc_ResultPanel.cpp"
#include "YPKJ5OE7LN/moc_RoleSelectorWidget.cpp"
